import type {
  Product,
  Category,
  Table,
  Order,
  User,
  Promotion,
  DailySales,
  ProductSales,
  BusinessSettings,
} from './types'

export const businessSettings: BusinessSettings = {
  name: 'Coty Café',
  logo: '/logo-coty-cafe.png',
  isOpen: true,
  openTime: '07:00',
  closeTime: '21:00',
  phone: '+52 55 1234 5678',
  address: 'Av. Reforma 123, Col. Centro, CDMX',
  instagram: 'cotycafe',
  facebook: 'cotycafe',
  whatsapp: '5215512345678',
  deliveryFee: 35,
  minOrderAmount: 100,
  taxRate: 0.16,
}

export const categories: Category[] = [
  { id: 'coffee', name: 'Café', icon: 'Coffee', order: 1 },
  { id: 'specialty', name: 'Especialidades', icon: 'Sparkles', order: 2 },
  { id: 'tea', name: 'Té', icon: 'Leaf', order: 3 },
  { id: 'cold', name: 'Bebidas Frías', icon: 'Snowflake', order: 4 },
  { id: 'pastry', name: 'Panadería', icon: 'Croissant', order: 5 },
  { id: 'food', name: 'Alimentos', icon: 'UtensilsCrossed', order: 6 },
  { id: 'dessert', name: 'Postres', icon: 'Cake', order: 7 },
]

export const products: Product[] = [
  // Coffee
  {
    id: 'americano',
    name: 'Americano',
    description: 'Espresso con agua caliente, intenso y aromático',
    price: 45,
    image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=400&h=400&fit=crop',
    categoryId: 'coffee',
    featured: false,
    available: true,
    preparationTime: 3,
    options: [
      {
        id: 'size',
        name: 'Tamaño',
        required: true,
        multiple: false,
        choices: [
          { id: 'small', name: 'Chico', priceModifier: 0 },
          { id: 'medium', name: 'Mediano', priceModifier: 10 },
          { id: 'large', name: 'Grande', priceModifier: 20 },
        ],
      },
      {
        id: 'extra',
        name: 'Extra',
        required: false,
        multiple: true,
        choices: [
          { id: 'extra-shot', name: 'Shot extra', priceModifier: 15 },
          { id: 'oat-milk', name: 'Leche de avena', priceModifier: 12 },
        ],
      },
    ],
  },
  {
    id: 'cappuccino',
    name: 'Cappuccino',
    description: 'Espresso con leche espumada y espuma de leche cremosa',
    price: 55,
    image: 'https://images.unsplash.com/photo-1572442388796-11668a67e53d?w=400&h=400&fit=crop',
    categoryId: 'coffee',
    featured: true,
    available: true,
    preparationTime: 4,
    options: [
      {
        id: 'size',
        name: 'Tamaño',
        required: true,
        multiple: false,
        choices: [
          { id: 'small', name: 'Chico', priceModifier: 0 },
          { id: 'medium', name: 'Mediano', priceModifier: 10 },
          { id: 'large', name: 'Grande', priceModifier: 20 },
        ],
      },
    ],
  },
  {
    id: 'latte',
    name: 'Latte',
    description: 'Espresso suave con abundante leche vaporizada',
    price: 58,
    image: 'https://images.unsplash.com/photo-1570968915860-54d5c301fa9f?w=400&h=400&fit=crop',
    categoryId: 'coffee',
    featured: true,
    available: true,
    preparationTime: 4,
    options: [
      {
        id: 'size',
        name: 'Tamaño',
        required: true,
        multiple: false,
        choices: [
          { id: 'small', name: 'Chico', priceModifier: 0 },
          { id: 'medium', name: 'Mediano', priceModifier: 10 },
          { id: 'large', name: 'Grande', priceModifier: 20 },
        ],
      },
      {
        id: 'flavor',
        name: 'Sabor',
        required: false,
        multiple: false,
        choices: [
          { id: 'vanilla', name: 'Vainilla', priceModifier: 10 },
          { id: 'caramel', name: 'Caramelo', priceModifier: 10 },
          { id: 'hazelnut', name: 'Avellana', priceModifier: 10 },
        ],
      },
    ],
  },
  {
    id: 'espresso',
    name: 'Espresso',
    description: 'Shot concentrado de café premium',
    price: 35,
    image: 'https://images.unsplash.com/photo-1510707577719-ae7c14805e3a?w=400&h=400&fit=crop',
    categoryId: 'coffee',
    featured: false,
    available: true,
    preparationTime: 2,
  },
  {
    id: 'mocha',
    name: 'Mocha',
    description: 'Espresso con chocolate y leche vaporizada',
    price: 65,
    image: 'https://images.unsplash.com/photo-1578314675249-a6910f80cc4e?w=400&h=400&fit=crop',
    categoryId: 'coffee',
    featured: false,
    available: true,
    preparationTime: 5,
  },
  // Specialty
  {
    id: 'flat-white',
    name: 'Flat White',
    description: 'Doble shot de espresso con microespuma de leche',
    price: 62,
    image: 'https://images.unsplash.com/photo-1577968897966-3d4325b36b61?w=400&h=400&fit=crop',
    categoryId: 'specialty',
    featured: true,
    available: true,
    preparationTime: 4,
  },
  {
    id: 'affogato',
    name: 'Affogato',
    description: 'Helado de vainilla con shot de espresso caliente',
    price: 75,
    image: 'https://images.unsplash.com/photo-1579992357154-faf4bde95b3d?w=400&h=400&fit=crop',
    categoryId: 'specialty',
    featured: true,
    available: true,
    preparationTime: 3,
  },
  {
    id: 'cold-brew',
    name: 'Cold Brew',
    description: 'Café extraído en frío durante 18 horas',
    price: 55,
    image: 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=400&h=400&fit=crop',
    categoryId: 'specialty',
    featured: false,
    available: true,
    preparationTime: 2,
  },
  // Tea
  {
    id: 'matcha-latte',
    name: 'Matcha Latte',
    description: 'Té verde matcha premium con leche',
    price: 68,
    image: 'https://images.unsplash.com/photo-1515823064-d6e0c04616a7?w=400&h=400&fit=crop',
    categoryId: 'tea',
    featured: true,
    available: true,
    preparationTime: 4,
  },
  {
    id: 'chai-latte',
    name: 'Chai Latte',
    description: 'Té chai especiado con leche espumada',
    price: 58,
    image: 'https://images.unsplash.com/photo-1557006021-b85faa2bc5e2?w=400&h=400&fit=crop',
    categoryId: 'tea',
    featured: false,
    available: true,
    preparationTime: 4,
  },
  {
    id: 'green-tea',
    name: 'Té Verde',
    description: 'Té verde orgánico de alta calidad',
    price: 38,
    image: 'https://images.unsplash.com/photo-1564890369478-c89ca6d9cde9?w=400&h=400&fit=crop',
    categoryId: 'tea',
    featured: false,
    available: true,
    preparationTime: 3,
  },
  // Cold drinks
  {
    id: 'iced-latte',
    name: 'Iced Latte',
    description: 'Latte frío con hielo',
    price: 58,
    image: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?w=400&h=400&fit=crop',
    categoryId: 'cold',
    featured: false,
    available: true,
    preparationTime: 3,
  },
  {
    id: 'frappe',
    name: 'Frappé',
    description: 'Bebida helada de café con crema batida',
    price: 72,
    image: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=400&h=400&fit=crop',
    categoryId: 'cold',
    featured: true,
    available: true,
    preparationTime: 5,
  },
  {
    id: 'smoothie',
    name: 'Smoothie de Frutos Rojos',
    description: 'Mezcla de fresas, frambuesas y moras con yogurt',
    price: 68,
    image: 'https://images.unsplash.com/photo-1553530666-ba11a7da3888?w=400&h=400&fit=crop',
    categoryId: 'cold',
    featured: false,
    available: true,
    preparationTime: 4,
  },
  // Pastry
  {
    id: 'croissant',
    name: 'Croissant',
    description: 'Croissant de mantequilla recién horneado',
    price: 42,
    image: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=400&h=400&fit=crop',
    categoryId: 'pastry',
    featured: true,
    available: true,
    preparationTime: 1,
  },
  {
    id: 'pain-au-chocolat',
    name: 'Pain au Chocolat',
    description: 'Hojaldre con chocolate belga',
    price: 48,
    image: 'https://images.unsplash.com/photo-1530610476181-d83430b64dcd?w=400&h=400&fit=crop',
    categoryId: 'pastry',
    featured: false,
    available: true,
    preparationTime: 1,
  },
  {
    id: 'muffin',
    name: 'Muffin de Arándano',
    description: 'Muffin esponjoso con arándanos frescos',
    price: 45,
    image: 'https://images.unsplash.com/photo-1607958996333-41aef7caefaa?w=400&h=400&fit=crop',
    categoryId: 'pastry',
    featured: false,
    available: true,
    preparationTime: 1,
  },
  // Food
  {
    id: 'avocado-toast',
    name: 'Avocado Toast',
    description: 'Pan artesanal con aguacate, huevo pochado y semillas',
    price: 95,
    image: 'https://images.unsplash.com/photo-1541519227354-08fa5d50c44d?w=400&h=400&fit=crop',
    categoryId: 'food',
    featured: true,
    available: true,
    preparationTime: 8,
  },
  {
    id: 'sandwich',
    name: 'Sándwich Club',
    description: 'Pollo, tocino, lechuga, tomate y mayonesa',
    price: 110,
    image: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=400&h=400&fit=crop',
    categoryId: 'food',
    featured: false,
    available: true,
    preparationTime: 10,
  },
  {
    id: 'bagel',
    name: 'Bagel con Salmón',
    description: 'Bagel con queso crema, salmón ahumado y alcaparras',
    price: 125,
    image: 'https://images.unsplash.com/photo-1585668292920-e6ef6eb4ed04?w=400&h=400&fit=crop',
    categoryId: 'food',
    featured: false,
    available: true,
    preparationTime: 5,
  },
  // Desserts
  {
    id: 'cheesecake',
    name: 'Cheesecake New York',
    description: 'Cheesecake cremoso con base de galleta',
    price: 85,
    image: 'https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=400&h=400&fit=crop',
    categoryId: 'dessert',
    featured: true,
    available: true,
    preparationTime: 1,
  },
  {
    id: 'brownie',
    name: 'Brownie con Helado',
    description: 'Brownie de chocolate con helado de vainilla',
    price: 78,
    image: 'https://images.unsplash.com/photo-1564355808539-22fda35bed7e?w=400&h=400&fit=crop',
    categoryId: 'dessert',
    featured: false,
    available: true,
    preparationTime: 2,
  },
  {
    id: 'tiramisu',
    name: 'Tiramisú',
    description: 'Clásico postre italiano con café y mascarpone',
    price: 88,
    image: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=400&h=400&fit=crop',
    categoryId: 'dessert',
    featured: false,
    available: true,
    preparationTime: 1,
  },
]

export const tables: Table[] = [
  { id: 't1', number: 1, capacity: 2, status: 'free' },
  { id: 't2', number: 2, capacity: 2, status: 'occupied', currentOrderId: 'o1', waitressId: 'w1' },
  { id: 't3', number: 3, capacity: 4, status: 'waiting', waitressId: 'w1' },
  { id: 't4', number: 4, capacity: 4, status: 'free' },
  { id: 't5', number: 5, capacity: 6, status: 'occupied', currentOrderId: 'o2', waitressId: 'w2' },
  { id: 't6', number: 6, capacity: 6, status: 'finished', currentOrderId: 'o3', waitressId: 'w1' },
  { id: 't7', number: 7, capacity: 4, status: 'free' },
  { id: 't8', number: 8, capacity: 2, status: 'occupied', currentOrderId: 'o4', waitressId: 'w2' },
  { id: 't9', number: 9, capacity: 8, status: 'free' },
  { id: 't10', number: 10, capacity: 4, status: 'waiting', waitressId: 'w1' },
]

export const users: User[] = [
  { id: 'admin1', name: 'María García', email: 'maria@cotycafe.com', role: 'admin', avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop' },
  { id: 'staff1', name: 'Carlos López', email: 'carlos@cotycafe.com', role: 'staff', avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop' },
  { id: 'w1', name: 'Ana Martínez', email: 'ana@cotycafe.com', role: 'staff', avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop' },
  { id: 'w2', name: 'Luis Hernández', email: 'luis@cotycafe.com', role: 'staff', avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop' },
]

export const orders: Order[] = [
  {
    id: 'o1',
    type: 'table',
    status: 'preparing',
    items: [
      { id: 'ci1', product: products[1], quantity: 2, selectedOptions: [{ optionId: 'size', choiceIds: ['medium'] }] },
      { id: 'ci2', product: products[14], quantity: 2, selectedOptions: [] },
    ],
    subtotal: 214,
    tax: 34.24,
    total: 248.24,
    paymentMethod: 'card',
    customerName: 'Mesa 2',
    customerPhone: '',
    tableId: 't2',
    createdAt: new Date(Date.now() - 15 * 60000),
    updatedAt: new Date(Date.now() - 5 * 60000),
  },
  {
    id: 'o2',
    type: 'table',
    status: 'confirmed',
    items: [
      { id: 'ci3', product: products[17], quantity: 1, selectedOptions: [] },
      { id: 'ci4', product: products[2], quantity: 3, selectedOptions: [{ optionId: 'size', choiceIds: ['large'] }] },
      { id: 'ci5', product: products[20], quantity: 1, selectedOptions: [] },
    ],
    subtotal: 414,
    tax: 66.24,
    total: 480.24,
    paymentMethod: 'cash',
    customerName: 'Mesa 5',
    customerPhone: '',
    tableId: 't5',
    createdAt: new Date(Date.now() - 25 * 60000),
    updatedAt: new Date(Date.now() - 20 * 60000),
  },
  {
    id: 'o3',
    type: 'table',
    status: 'completed',
    items: [
      { id: 'ci6', product: products[0], quantity: 2, selectedOptions: [{ optionId: 'size', choiceIds: ['small'] }] },
    ],
    subtotal: 90,
    tax: 14.40,
    total: 104.40,
    paymentMethod: 'card',
    customerName: 'Mesa 6',
    customerPhone: '',
    tableId: 't6',
    createdAt: new Date(Date.now() - 60 * 60000),
    updatedAt: new Date(Date.now() - 30 * 60000),
  },
  {
    id: 'o4',
    type: 'table',
    status: 'preparing',
    items: [
      { id: 'ci7', product: products[8], quantity: 2, selectedOptions: [] },
    ],
    subtotal: 136,
    tax: 21.76,
    total: 157.76,
    paymentMethod: 'cash',
    customerName: 'Mesa 8',
    customerPhone: '',
    tableId: 't8',
    createdAt: new Date(Date.now() - 10 * 60000),
    updatedAt: new Date(Date.now() - 8 * 60000),
  },
  {
    id: 'o5',
    type: 'delivery',
    status: 'pending',
    items: [
      { id: 'ci8', product: products[1], quantity: 1, selectedOptions: [{ optionId: 'size', choiceIds: ['large'] }] },
      { id: 'ci9', product: products[20], quantity: 1, selectedOptions: [] },
    ],
    subtotal: 160,
    tax: 25.60,
    total: 220.60,
    paymentMethod: 'transfer',
    customerName: 'Roberto Sánchez',
    customerPhone: '+52 55 9876 5432',
    customerAddress: 'Calle Madero 456, Col. Centro',
    createdAt: new Date(Date.now() - 5 * 60000),
    updatedAt: new Date(Date.now() - 5 * 60000),
  },
  {
    id: 'o6',
    type: 'pickup',
    status: 'ready',
    items: [
      { id: 'ci10', product: products[5], quantity: 1, selectedOptions: [] },
      { id: 'ci11', product: products[14], quantity: 1, selectedOptions: [] },
    ],
    subtotal: 104,
    tax: 16.64,
    total: 120.64,
    paymentMethod: 'card',
    customerName: 'Patricia Ruiz',
    customerPhone: '+52 55 1111 2222',
    createdAt: new Date(Date.now() - 20 * 60000),
    updatedAt: new Date(Date.now() - 2 * 60000),
  },
]

export const promotions: Promotion[] = [
  {
    id: 'promo1',
    title: '2x1 en Cappuccinos',
    description: 'Todos los miércoles, llévate dos cappuccinos por el precio de uno',
    image: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=600&h=300&fit=crop',
    discount: 50,
    validFrom: new Date('2024-01-01'),
    validTo: new Date('2024-12-31'),
    productIds: ['cappuccino'],
    active: true,
  },
  {
    id: 'promo2',
    title: 'Desayuno Completo',
    description: 'Avocado Toast + Café Americano por solo $120',
    image: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?w=600&h=300&fit=crop',
    discount: 15,
    validFrom: new Date('2024-01-01'),
    validTo: new Date('2024-12-31'),
    productIds: ['avocado-toast', 'americano'],
    active: true,
  },
  {
    id: 'promo3',
    title: 'Happy Hour',
    description: '20% de descuento en bebidas frías de 3pm a 5pm',
    image: 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=600&h=300&fit=crop',
    discount: 20,
    validFrom: new Date('2024-01-01'),
    validTo: new Date('2024-12-31'),
    categoryIds: ['cold'],
    active: true,
  },
]

export const dailySales: DailySales[] = [
  { date: '2024-01-15', revenue: 8450, orders: 67 },
  { date: '2024-01-16', revenue: 9200, orders: 73 },
  { date: '2024-01-17', revenue: 7800, orders: 62 },
  { date: '2024-01-18', revenue: 10500, orders: 84 },
  { date: '2024-01-19', revenue: 12300, orders: 98 },
  { date: '2024-01-20', revenue: 11800, orders: 94 },
  { date: '2024-01-21', revenue: 9600, orders: 76 },
]

export const productSales: ProductSales[] = [
  { productId: 'cappuccino', productName: 'Cappuccino', quantity: 156, revenue: 8580 },
  { productId: 'latte', productName: 'Latte', quantity: 142, revenue: 8236 },
  { productId: 'americano', productName: 'Americano', quantity: 128, revenue: 5760 },
  { productId: 'croissant', productName: 'Croissant', quantity: 98, revenue: 4116 },
  { productId: 'avocado-toast', productName: 'Avocado Toast', quantity: 76, revenue: 7220 },
  { productId: 'frappe', productName: 'Frappé', quantity: 68, revenue: 4896 },
  { productId: 'cheesecake', productName: 'Cheesecake', quantity: 54, revenue: 4590 },
]
